-- =============================================================================
-- LAYER 1 - Transactional star schema (populated by ETL)
-- =============================================================================

-- Hour-level date dimension.
CREATE TABLE dim_date (
    date_key      INT          PRIMARY KEY,
    date          DATE         NOT NULL,
    day           SMALLINT     NOT NULL CHECK (day BETWEEN 1 AND 31),
    month         SMALLINT     NOT NULL CHECK (month BETWEEN 1 AND 12),
    quarter       SMALLINT     NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    year          SMALLINT     NOT NULL,
    weekday       SMALLINT     NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    hour          SMALLINT     NOT NULL CHECK (hour BETWEEN 0 AND 23),
    is_weekend    BOOLEAN      NOT NULL
);


CREATE TABLE dim_customer (
    user_id        INT          PRIMARY KEY,
    total_orders   INT          NOT NULL DEFAULT 0 CHECK (total_orders >= 0)
);


-- Product dimension with denormalized aisle and department attributes.
CREATE TABLE dim_product (
    product_id      INT          PRIMARY KEY,
    product_name    TEXT         NOT NULL,
    category_id     INT          NOT NULL,
    category        TEXT         NOT NULL,
    department_id   INT          NOT NULL,
    department      TEXT         NOT NULL
);


CREATE TABLE dim_order (
    order_id                INT          PRIMARY KEY,
    order_number            INT          NOT NULL CHECK (order_number > 0),
    days_since_prior_order  REAL         NULL
);


-- Grain: one row per product in one order.
CREATE TABLE fact_order_items (
    order_item_key      BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id            INT          NOT NULL REFERENCES dim_order(order_id),
    user_id             INT          NOT NULL REFERENCES dim_customer(user_id),
    product_id          INT          NOT NULL REFERENCES dim_product(product_id),
    date_key            INT          NOT NULL REFERENCES dim_date(date_key),
    add_to_cart_order   SMALLINT     NOT NULL CHECK (add_to_cart_order > 0),
    reordered           SMALLINT     NOT NULL CHECK (reordered IN (0,1)),
    quantity            SMALLINT     NOT NULL DEFAULT 1 CHECK (quantity > 0),
    UNIQUE (order_id, product_id)
);


-- =============================================================================
-- LAYER 2 - Mining output (populated by the batch mining job)
-- =============================================================================

-- Mining run metadata.
CREATE TABLE dim_mining_run (
    run_id            TEXT         PRIMARY KEY,
    run_date          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    algorithm         TEXT         NOT NULL CHECK (algorithm IN ('apriori','fp_growth','eclat')),
    min_support       REAL         NOT NULL CHECK (min_support > 0 AND min_support <= 1),
    min_confidence    REAL         NOT NULL CHECK (min_confidence > 0 AND min_confidence <= 1),
    granularity       TEXT         NOT NULL CHECK (granularity IN ('product','aisle','department')),
    runtime_seconds   REAL         NULL CHECK (runtime_seconds IS NULL OR runtime_seconds >= 0),
    rules_generated   INT          NULL CHECK (rules_generated IS NULL OR rules_generated >= 0),
    notes             TEXT         NULL
);


-- Frequent itemsets generated by a mining run.
CREATE TABLE fact_frequent_itemsets (
    itemset_key     BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    items           INTEGER[]    NOT NULL,
    itemset_size    SMALLINT     NOT NULL CHECK (itemset_size >= 1),
    support_count   INT          NOT NULL CHECK (support_count > 0),
    support         REAL         NOT NULL CHECK (support > 0 AND support <= 1),
    granularity     TEXT         NOT NULL CHECK (granularity IN ('product','aisle','department')),
    run_id          TEXT         NOT NULL REFERENCES dim_mining_run(run_id) ON DELETE CASCADE,
    CHECK (cardinality(items) = itemset_size),
    UNIQUE (run_id, granularity, items)
);


-- Association rules generated by a mining run.
-- IDs are interpreted by granularity:
--   product    -> product_id
--   aisle      -> category_id / aisle_id
--   department -> department_id
CREATE TABLE fact_association_rules (
    rule_key                BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    antecedent              INTEGER[]    NOT NULL,
    antecedent_size         SMALLINT     NOT NULL CHECK (antecedent_size >= 1),
    consequent_id           INT          NOT NULL,
    consequent_name         TEXT         NULL,
    support                 REAL         NOT NULL CHECK (support > 0 AND support <= 1),
    confidence              REAL         NOT NULL CHECK (confidence > 0 AND confidence <= 1),
    lift                    REAL         NOT NULL CHECK (lift > 0),
    granularity             TEXT         NOT NULL CHECK (granularity IN ('product','aisle','department')),
    run_id                  TEXT         NOT NULL REFERENCES dim_mining_run(run_id) ON DELETE CASCADE,
    CHECK (cardinality(antecedent) = antecedent_size),
    UNIQUE (run_id, granularity, antecedent, consequent_id)
);


-- Personalized product recommendations generated from association rules.
CREATE TABLE fact_user_recommendations (
    recommendation_key       BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id                  INT          NOT NULL REFERENCES dim_customer(user_id),
    recommended_product_id   INT          NOT NULL REFERENCES dim_product(product_id),
    source_rule_key          BIGINT       NOT NULL REFERENCES fact_association_rules(rule_key) ON DELETE CASCADE,
    recommendation_rank      SMALLINT     NOT NULL CHECK (recommendation_rank > 0),
    score                    REAL         NOT NULL CHECK (score > 0),
    generated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    run_id                   TEXT         NOT NULL REFERENCES dim_mining_run(run_id) ON DELETE CASCADE,
    UNIQUE (run_id, user_id, recommendation_rank),
    UNIQUE (run_id, user_id, recommended_product_id)
);
